# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressID', models.CharField(max_length=18)),
                ('Hostname', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=18)),
                ('Cidr', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostID', models.CharField(max_length=12)),
                ('IP', models.CharField(max_length=15)),
                ('Hostname', models.CharField(max_length=75)),
                ('DeviceType', models.CharField(max_length=25)),
                ('OS', models.CharField(max_length=25)),
                ('Rating', models.CharField(max_length=10)),
                ('Reviewed', models.BooleanField(default=False)),
                ('Category', models.CharField(max_length=25)),
                ('LastSeen', models.CharField(max_length=100)),
                ('Stale', models.BooleanField(default=False)),
                ('StaleLevel', models.IntegerField(default=0)),
                ('addresses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Web_Scout.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntID', models.CharField(max_length=25)),
                ('Port', models.CharField(max_length=6)),
                ('Name', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('Version', models.CharField(max_length=100)),
                ('Banner', models.CharField(max_length=300)),
                ('ImgLink', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=500)),
                ('Url', models.CharField(max_length=35)),
                ('DefaultCreds', models.BooleanField(default=False)),
                ('HttpAuth', models.BooleanField(default=False)),
                ('Default_Credentials', models.CharField(max_length=100)),
                ('Retry', models.BooleanField(default=False)),
                ('Module', models.CharField(max_length=6)),
                ('Type', models.CharField(max_length=4)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Scout.Hosts')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=25)),
                ('Task_Id', models.CharField(max_length=75)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
    ]
