# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=15)),
                ('Hostname', models.CharField(max_length=75)),
                ('DeviceType', models.CharField(max_length=25)),
                ('OS', models.CharField(max_length=25)),
                ('Rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortID', models.CharField(max_length=25)),
                ('Port', models.CharField(max_length=6)),
                ('Name', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('Version', models.CharField(max_length=100)),
                ('Extra_Info', models.CharField(max_length=200)),
                ('Banner', models.CharField(max_length=300)),
                ('ImgLink', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=35)),
                ('DefaultCreds', models.BooleanField(default=False)),
                ('HttpAuth', models.BooleanField(default=False)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Scout.Hosts')),
            ],
        ),
    ]
