# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=25)),
                ('task_id', models.CharField(max_length=75)),
            ],
        ),
    ]
