# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Scout', '0002_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_id',
            new_name='Task_Id',
        ),
    ]
