# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Scout', '0003_auto_20160720_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='Reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
