# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=25)),
                ('Message', models.CharField(max_length=150)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
